const projects = [
  {
    id: "0",
    tag: "Frontend",
    name: "CryptoBase",
    projectLink: "https://bl-crypto.netlify.app/",
    codeLink: "https://github.com/BouakkazLotfiG/crypto-app",
    imgUrl: require("../src/assets/portfolio/cryptoBase.PNG"),
    desc: "A cryptocurrency web application displaying updated informations about the top 10 crypto in the world",
    tech: "React, Mongodb, GraphQl",
    logo: require("../src/assets/projectsLogo/crypto.png"),
  },
  {
    id: "1",
    tag: "Frontend",
    name: "Hoobank",
    projectLink: "https://bl-bank.netlify.app/",
    codeLink: "https://github.com/BouakkazLotfiG/bank-app",
    imgUrl: require("../src/assets/portfolio/hoobank.PNG"),
    desc: "A modern bank Website ",
    tech: "React, Mongodb, GraphQl",
    logo: require("../src/assets/projectsLogo/hoobank.png"),
  },
  {
    id: "2",
    tag: "Frontend",
    name: "Netflix",
    projectLink: "https://bl-netflix.netlify.app/",
    codeLink: "https://github.com/BouakkazLotfiG/netflix-clone",
    imgUrl: require("../src/assets/portfolio/netflix.PNG"),
    desc: "Netflix clone",
    tech: "React, Mongodb, GraphQl",
    logo: require("../src/assets/projectsLogo/Netflix.png"),
  },
  {
    id: "3",
    tag: "Full stack",
    name: "Project Manager",
    projectLink: "google.com",
    codeLink: "https://github.com/BouakkazLotfiG/project-manager",
    imgUrl: require("../src/assets/portfolio/cryptoBase.PNG"),
    desc: "this proket is goooooooood",
    tech: "React, Mongodb, GraphQl",
    logo: require("../src/assets/projectsLogo/hoobank.png"),
  },
  {
    id: "4",
    tag: "Full stack",
    name: "TikTok",
    projectLink: "google.com",
    codeLink: "github.com",
    imgUrl: require("../src/assets/portfolio/cryptoBase.PNG"),
    desc: "TikTok Clone",
    tech: "TypeScript, Nextjs, React, Mongodb, GraphQl",
    logo: require("../src/assets/projectsLogo/hoobank.png"),
  },
  {
    id: "5",
    tag: "Full stack",
    name: "ToDo",
    projectLink: "google.com",
    codeLink: "github.com",
    imgUrl: require("../src/assets/portfolio/cryptoBase.PNG"),
    desc: "this proket is goooooooood",
    tech: "React, Mongodb, GraphQl",
    logo: require("../src/assets/projectsLogo/hoobank.png"),
  },
];

module.exports = { projects };
