const projects = [
  {
    id: "0",
    tag: "React",
    name: "CryptoBase",
    projectLink: "https://bl-crypto.netlify.app/",
    codeLink: "https://github.com/BouakkazLotfiG/crypto-app",
    imgUrl: require("../src/assets/portfolio/cryptoBase.PNG"),
    desc: "CryptoBase is a fully responsive cryptocurrency website, Responsive for all devices, build using HTML, CSS, and React.",
    tech: "React, Firebase, Light/Dark mode",
    logo: require("../src/assets/projectsLogo/crypto.png"),
  },
  {
    id: "1",
    tag: "React",
    name: "Hoobank",
    projectLink: "https://bl-bank.netlify.app/",
    codeLink: "https://github.com/BouakkazLotfiG/bank-app",
    imgUrl: require("../src/assets/portfolio/hoobank.PNG"),
    desc: "HooBank - Modern UI/UX website displaying main advantages and services thta HooBank provides",
    tech: "React, Tailwind CSS",
    logo: require("../src/assets/projectsLogo/hoobank.png"),
  },
  {
    id: "2",
    tag: "React",
    name: "Netflix",
    projectLink: "https://bl-netflix.netlify.app/",
    codeLink: "https://github.com/BouakkazLotfiG/netflix-clone",
    imgUrl: require("../src/assets/portfolio/netflix.PNG"),
    desc: "A Netflix clone displaying diffrent categories of movies using the TMDB Api",
    tech: "React, Firebase",
    logo: require("../src/assets/projectsLogo/Netflix.png"),
  },
  {
    id: "3",
    tag: "React",
    name: "Spotify",
    projectLink: "https://bl-spotify.netlify.app/",
    codeLink: "https://github.com/BouakkazLotfiG/Spotify-clone",
    imgUrl: require("../src/assets/portfolio/spotify.PNG"),
    desc: "Spotify clone, displays top charts and artists",
    tech: "React, Redux, RapidApi, Tailwind",
    logo: require("../src/assets/projectsLogo/spotify.png"),
  },
  {
    id: "4",
    tag: "Angular",
    name: "TikTok",
    projectLink: "google.com",
    codeLink: "github.com",
    imgUrl: require("../src/assets/portfolio/cryptoBase.PNG"),
    desc: "TikTok Clone",
    tech: "TypeScript, Nextjs, React, Mongodb, GraphQl",
    logo: require("../src/assets/projectsLogo/hoobank.png"),
  },
  {
    id: "5",
    tag: "Angular",
    name: "ToDo",
    projectLink: "google.com",
    codeLink: "github.com",
    imgUrl: require("../src/assets/portfolio/cryptoBase.PNG"),
    desc: "this proket is goooooooood",
    tech: "React, Mongodb, GraphQl",
    logo: require("../src/assets/projectsLogo/hoobank.png"),
  },
];

module.exports = { projects };
